### ISSUE TITLE
Is using this lib still the preferred way of getting constraints references from views ?

### ISSUE THREAD

**Issue by AnthoPakPak** [keshavvishwkarma/KVConstraintExtensionsMaster#1]
Hi Keshav Vishwkarma, 

I've just found this library thanks to [your post on SO](https://stackoverflow.com/a/33986177/4894980). Indeed, I was searching for an easy way to get constraints from view. I've just tried your lib and it seems to do the job well.

As this library is not highly maintained, I was wondering if this was still your preferred way for getting constraints from views, or did you find new better ways/libraries to access them ? Any caveat that are good to be aware before using this lib ?

Thanks in advance for your answer :)

**Comment by keshavvishwkarma** [comment]
@AnthoPakPak Sorry for the late reply, but I’m happy to know that this library and [my post on SO](https://stackoverflow.com/questions/33971298/ios-8-find-constraints-for-a-uiview-with-identifier/33986177#33986177) are useful for you.

The mechanism that I used in this library is still the best way to access constraint from any view and it is working perfectly with no issue on any version on iOS from 7.0 to latest one.

But for the Swift project, you should use [KVConstraintKit](https://github.com/keshavvishwkarma/KVConstraintKit) because It's an advanced version of [KVConstraintExtensionsMaster]( https://github.com/keshavvishwkarma/KVConstraintExtensionsMaster ) using the advanced feature of Swift programming language like operator overloading

I haven’t found any issue in it that’s why you haven’t seen any comments for a long time. If you find any issue then you can contribute through pull requests and report issues on GitHub
